### ISSUE TITLE
Missing creatures after "Zhur-Taa Druid"

### ISSUE THREAD

**Issue by invisible-walrus** [oboyone/mb_thermal_printer#1]
After creating the creatures_images.json, no creature after Zhur-taa druid alphabetically appears. 

Script stopped after payload 207, even after multiple runs

**Comment by Haplo064** [comment]
It's due to the last payload not actually getting called:
https://github.com/oboyone/mb_thermal_printer/blob/684cbb17f390edb640cf99fa3d384d8c4f084286/get_image_urls_from_scryfall.py#L32C5-L32C21

This will only send a payload when it gets to 70 cards, so the last call (under 70 cards) will never be made.

**Comment by Haplo064** [comment]
@invisible-walrus I fixed it, and improved it a fair bit.
It was also missing all transform and modal dfc cards, for instance.
This version also allows you to resume from a crash, or update files for new sets without going over it all again.

https://github.com/Haplo064/Mormir-Vig/blob/main/getCards.py

**Comment by oboyone** [comment]
Added a check now if it is the last loop so that it will send the payload
